# Generated by Django 3.2.9 on 2021-12-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdetails',
            fields=[
                ('Book_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Book_Title', models.CharField(max_length=500)),
                ('Author_Name', models.CharField(max_length=500)),
                ('Reserved', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=1000)),
                ('usercomment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservationdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
                ('BookTitle', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('Student_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=500)),
                ('Last_Name', models.CharField(max_length=500)),
                ('Major', models.CharField(max_length=500)),
                ('Year', models.CharField(max_length=500)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
